---
  version: '3.7'
  services:
    db-lecture:
      image: mysql:8.0.12
      volumes:
        - ./db:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: "mamram"
      ports:
        - "4306:3306"
